export const INBOX_ABI = [
  {
    type: "event",
    name: "MessageSent",
    inputs: [
      { name: "requestId", type: "bytes32", indexed: true },
      { name: "targetChainId", type: "uint256", indexed: true },
      { name: "targetContract", type: "address", indexed: true },
      { name: "methodSelector", type: "bytes4", indexed: false },
      { name: "methodCallHash", type: "bytes32", indexed: false },
      { name: "dataLength", type: "uint256", indexed: false },
      { name: "datatypeCount", type: "uint16", indexed: false },
      { name: "datalenCount", type: "uint16", indexed: false },
      { name: "callbackSelector", type: "bytes4", indexed: false },
      { name: "errorSelector", type: "bytes4", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MessageReceived",
    inputs: [
      { name: "requestId", type: "bytes32", indexed: true },
      { name: "sourceChainId", type: "uint256", indexed: true },
      { name: "sourceContract", type: "address", indexed: true },
      { name: "methodSelector", type: "bytes4", indexed: false },
      { name: "methodCallHash", type: "bytes32", indexed: false },
      { name: "dataLength", type: "uint256", indexed: false },
      { name: "datatypeCount", type: "uint16", indexed: false },
      { name: "datalenCount", type: "uint16", indexed: false },
    ],
  },
  {
    type: "function",
    name: "getRequests",
    stateMutability: "view",
    inputs: [
      { name: "targetChainId", type: "uint256" },
      { name: "from", type: "uint256" },
      { name: "len", type: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "requestId", type: "bytes32" },
          { name: "targetChainId", type: "uint256" },
          { name: "targetContract", type: "address" },
          {
            name: "methodCall",
            type: "tuple",
            components: [
              { name: "selector", type: "bytes4" },
              { name: "data", type: "bytes" },
              { name: "datatypes", type: "bytes8[]" },
              { name: "datalens", type: "bytes32[]" },
            ],
          },
          { name: "callerContract", type: "address" },
          { name: "originalSender", type: "address" },
          { name: "timestamp", type: "uint64" },
          { name: "callbackSelector", type: "bytes4" },
          { name: "errorSelector", type: "bytes4" },
          { name: "isTwoWay", type: "bool" },
          { name: "executed", type: "bool" },
          { name: "sourceRequestId", type: "bytes32" },
          { name: "targetFee", type: "uint256" },
          { name: "callerFee", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getRequestsLen",
    stateMutability: "view",
    inputs: [{ name: "targetChainId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "incomingRequests",
    stateMutability: "view",
    inputs: [{ name: "requestId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "requestId", type: "bytes32" },
          { name: "targetChainId", type: "uint256" },
          { name: "targetContract", type: "address" },
          {
            name: "methodCall",
            type: "tuple",
            components: [
              { name: "selector", type: "bytes4" },
              { name: "data", type: "bytes" },
              { name: "datatypes", type: "bytes8[]" },
              { name: "datalens", type: "bytes32[]" },
            ],
          },
          { name: "callerContract", type: "address" },
          { name: "originalSender", type: "address" },
          { name: "timestamp", type: "uint64" },
          { name: "callbackSelector", type: "bytes4" },
          { name: "errorSelector", type: "bytes4" },
          { name: "isTwoWay", type: "bool" },
          { name: "executed", type: "bool" },
          { name: "sourceRequestId", type: "bytes32" },
          { name: "targetFee", type: "uint256" },
          { name: "callerFee", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "lastIncomingRequestId",
    stateMutability: "view",
    inputs: [{ name: "sourceChainId", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "batchProcessRequests",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sourceChainId", type: "uint256" },
      {
        name: "mined",
        type: "tuple[]",
        components: [
          { name: "requestId", type: "bytes32" },
          { name: "sourceContract", type: "address" },
          { name: "targetContract", type: "address" },
          {
            name: "methodCall",
            type: "tuple",
            components: [
              { name: "selector", type: "bytes4" },
              { name: "data", type: "bytes" },
              { name: "datatypes", type: "bytes8[]" },
              { name: "datalens", type: "bytes32[]" },
            ],
          },
          { name: "callbackSelector", type: "bytes4" },
          { name: "errorSelector", type: "bytes4" },
          { name: "isTwoWay", type: "bool" },
          { name: "sourceRequestId", type: "bytes32" },
          { name: "targetFee", type: "uint256" },
          { name: "callerFee", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
] as const;

